// <auto-generated />
using System;
using AutoGermanaBackEnd.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AutoGermanaBackEnd.Migrations
{
    [DbContext(typeof(dbproductosContext))]
    [Migration("20221226220822_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AutoGermanaBackEnd.Models.categoria", b =>
                {
                    b.Property<Guid>("idcategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("idcategoria");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("AutoGermanaBackEnd.Models.producto", b =>
                {
                    b.Property<Guid>("idproducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("Categoriaidcategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("codigo")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<Guid>("idcategoria")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("imagen")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("precio_venta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("idproducto");

                    b.HasIndex("Categoriaidcategoria");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("AutoGermanaBackEnd.Models.producto", b =>
                {
                    b.HasOne("AutoGermanaBackEnd.Models.categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Categoriaidcategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AutoGermanaBackEnd.Models.categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
